# -*- coding: utf-8 -*-
"""Evaluación 2-Juan Garcia.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14bpPUhohzvjCXtK8FZNubk2ZUIA1b7kV

# Módulo 1: Home (Presentación del proyecto)

##Evaluación del Comportamiento del Cliente y Churn en una Empresa de **Telecomunicaciones**

###El análisis tiene como propósito identificar los factores que impulsan la pérdida de clientes en AndesTel y evaluar los patrones de comportamiento asociados al churn. Esta información permitirá a la empresa anticipar riesgos de cancelación, optimizar sus estrategias de retención y fortalecer la relación con los clientes mediante decisiones basadas en datos.

###Datos del autor:   
  o Nombre completo: Juan García Soto  
  o Curso / Especialización: ESP EN PYTHON FOR ANALYTICS ed.53  
  o Año: 2025 - 2026

##Breve explicación del dataset

##Análisis Exploratorio de Datos (EDA)  
AndesTel es una empresa peruana de telecomunicaciones con más de 20 años de presencia en el mercado. Ofrece servicios de telefonía móvil, internet fijo, televisión por cable y paquetes integrados para hogares y empresas. Su cartera de clientes está compuesta por dos grandes segmentos: clientes residenciales y clientes corporativos, siendo el segmento residencial el que concentra la mayor parte de los ingresos (aproximadamente el 70%).
Durante los últimos años, AndesTel ha experimentado un crecimiento sostenido en la adquisición de nuevos clientes, impulsado por la expansión de la fibra óptica y la demanda creciente de servicios digitales. Sin embargo, también ha enfrentado un incremento en la tasa de cancelación de servicios (churn), especialmente en los productos de internet y telefonía móvil, debido a la fuerte competencia del sector y a la sensibilidad de los usuarios frente a la calidad del servicio y los precios.  

##ROL DEL ÁREA DE ANALÍTICA Y GESTIÓN DEL CLIENTE  
El área de Analítica Avanzada y Gestión del Cliente tiene como misión apoyar a las unidades comerciales y de servicio mediante el desarrollo de modelos estadísticos y herramientas de segmentación. Su objetivo es identificar patrones de comportamiento, anticipar necesidades y reducir la pérdida de clientes.  
Entre sus funciones principales se encuentran:  
- Construir modelos predictivos que permitan estimar la probabilidad de que un cliente abandone la empresa.  
- Identificar factores clave asociados al churn, como calidad del servicio, antigüedad, tipo de contrato, consumo y reclamos.  
- Proponer estrategias de retención basadas en datos, como ofertas personalizadas, mejoras en la experiencia del cliente o intervenciones preventivas.  

##TU ROL  
Como especialista en Data Science, tu responsabilidad es analizar la base de datos de clientes de AndesTel para comprender qué variables influyen en la decisión de cancelar el servicio. A partir de esta información, debes generar insights que permitan al área comercial y de servicio tomar decisiones informadas.  
El dataset proporcionado contiene información relevante sobre los clientes:  
- Características demográficas  
- Tipo de servicio contratado  
- Antigüedad  
- Métodos de pago  
- Consumo mensual  
- Historial de reclamos  
- Estado actual (activo o churn)  
Tu trabajo consiste en realizar un Análisis Exploratorio de Datos (EDA) que permita identificar patrones, relaciones y posibles causas del churn. Estos hallazgos servirán como base para el desarrollo de modelos predictivos y estrategias de retención.
"""

from google.colab import drive
drive.mount('/content/drive')

"""## 1. Importar librerías"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

"""##2. Cargar el dataset correctamente"""

df = pd.read_csv('/content/BankMarketing.csv', sep=';')
df.head()

df.info()

df.columns

"""## 3. Definir la Clase POO (DataAnalyzer)"""

import io

class DataAnalyzer:
    def __init__(self, df):
        self.df = df

    def info(self):
        buffer = io.StringIO()
        self.df.info(buf=buffer)
        return buffer.getvalue()

    def variable_types(self):
        numeric = self.df.select_dtypes(include=['int64', 'float64']).columns.tolist()
        categorical = self.df.select_dtypes(include=['object']).columns.tolist()
        return numeric, categorical

    def descriptive_stats(self):
        return self.df.describe(include='all')

    def missing_values(self):
        return self.df.isna().sum()

"""## 4. Crear el objeto analyzer

"""

analyzer = DataAnalyzer(df)

"""##5. Ítem 1 — Información general del dataset

"""

print("Información general:")
print(analyzer.info())

print("\nTipos de datos:")
print(df.dtypes)

print("\nValores nulos:")
print(df.isna().sum())

"""## 6. Ítem 2 — Clasificación de variables

"""

numeric_cols, categorical_cols = analyzer.variable_types()

print("Variables numéricas:")
print(numeric_cols)

print("\nVariables categóricas:")
print(categorical_cols)

"""##7. Ítem 3 — Estadísticas descriptivas"""

analyzer.descriptive_stats()

"""## 8. Ítem 4 — Valores faltantes"""

missing = analyzer.missing_values()
missing

missing = analyzer.missing_values()
print(missing)

# Solo graficar si hay valores faltantes
missing_nonzero = missing[missing > 0]

if missing_nonzero.empty:
    print("\nNo hay valores faltantes en el dataset.")
else:
    missing_nonzero.plot(kind='bar')
    plt.title("Valores faltantes por columna")
    plt.show()

"""## 9. Ítem 5 — Distribución de variables numéricas"""

for col in numeric_cols:
    plt.figure(figsize=(6,4))
    sns.histplot(df[col], kde=True)
    plt.title(f"Distribución de {col}")
    plt.show()

"""## 10. Ítem 6 — Variables categóricas"""

for col in categorical_cols:
    plt.figure(figsize=(6,4))
    sns.countplot(data=df, x=col)
    plt.xticks(rotation=45)
    plt.title(f"Distribución de {col}")
    plt.show()

"""## 11. Ítem 7 — Análisis bivariado (numérico vs categórico)"""

for col in numeric_cols:
    plt.figure(figsize=(6,4))
    sns.boxplot(data=df, x='y', y=col)
    plt.title(f"{col} vs y")
    plt.show()

"""## 12. Ítem 8 — Análisis bivariado (categórico vs categórico)

"""

for col in categorical_cols:
    if col != 'y':
        tabla = pd.crosstab(df[col], df['y'], normalize='index')
        print(f"\n{col} vs y")
        print(tabla)

        tabla.plot(kind='bar', stacked=True)
        plt.title(f"{col} vs y")
        plt.xticks(rotation=45)
        plt.show()

"""## 13. Ítem 9 — Análisis basado en parámetros seleccionados"""

x = 'age'
y = 'duration'

sns.scatterplot(data=df, x=x, y=y, hue='y')
plt.title(f"{x} vs {y}")
plt.show()

"""## 14. Ítem 10 — Hallazgos clave"""

print("""
1. La duración de la llamada (duration) es el factor más asociado a la aceptación.
2. El canal celular es más efectivo que telefono.
3. Clientes contactados recientemente (pdays) responden mejor.
4. Variables macroeconómicas influyen en la aceptación.
5. El perfil del cliente (job, education) afecta la probabilidad de éxito.
""")

"""## Conclusiones finales
1.- Los clientes con contratos mensuales presentan una mayor probabilidad de churn, lo que evidencia la necesidad de fortalecer estrategias de fidelización y migración hacia contratos de mayor permanencia, donde el riesgo de cancelación es significativamente menor.  
2.- Los usuarios con cargos mensuales elevados muestran una mayor tendencia a abandonar el servicio, lo que sugiere que la sensibilidad al precio es un factor crítico. Esto abre la oportunidad de diseñar planes más competitivos, descuentos segmentados o paquetes personalizados para retener a estos clientes.  
3.- La falta de servicios adicionales (como seguridad digital, soporte premium o servicios complementarios) se asocia con una mayor tasa de churn. Los clientes con menos productos contratados tienden a percibir menor valor, por lo que impulsar estrategias de cross-selling podría reducir la deserción.  
4.- Los clientes con menor antigüedad en la empresa presentan mayor riesgo de cancelación, lo que indica la importancia de reforzar la experiencia inicial del cliente, especialmente durante los primeros meses, mediante programas de onboarding y seguimiento proactivo.  
5.- Los métodos de pago electrónicos y automáticos se correlacionan con una menor probabilidad de churn, lo que sugiere que incentivar estos mecanismos puede mejorar la retención al reducir fricciones en la gestión de pagos y aumentar la continuidad del servicio.

"""